version: "3"

services:

  db:
    image: mariadb:${MARIADB_VERSION:-10.7}
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: ${DB_NAME:-wordpress}
      MYSQL_USER: ${DB_USER:-wordpress}
      MYSQL_PASSWORD: ${DB_PASS:-password}
    networks:
      - backend

  wordpress:
    depends_on:
      - db
    image: wordpress:${WORDPRESS_VERSION:-fpm-alpine}
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${DB_NAME:-wordpress}
      WORDPRESS_DB_USER: ${DB_USER:-wordpress}
      WORDPRESS_DB_PASSWORD: ${DB_PASS:-password}
      WORDPRESS_DEBUG: ${WP_DEBUG:-1}
      WORDPRESS_CONFIG_EXTRA: |
        /* Redis Ojbect Cache */
        define( 'WP_REDIS_HOST', 'redis' );
        define( 'WP_REDIS_PORT', 6379 );
    volumes:
      - wp_core:/var/www/html
      - wp_uploads:/var/www/html/wp-content/uploads
      - ./wordpress/plugins:/var/www/html/wp-content/plugins
      - ./wordpress/themes:/var/www/html/wp-content/themes
      - ./conf/${CONF_PHP:-php.dev.ini}:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - frontend
      - backend

  wpcli:
    depends_on:
      - db
      - wordpress
    image: wordpress:cli
    user: xfs
    volumes:
      - wp_core:/var/www/html
      - wp_uploads:/var/www/html/wp-content/uploads
      - ./wordpress/plugins:/var/www/html/wp-content/plugins
      - ./wordpress/themes:/var/www/html/wp-content/themes
    networks:
      - backend

  nginx:
    depends_on:
      - wordpress
    image: nginx:${NGINX_VERSION:-alpine}
    restart: always
    environment:
      - NGINX_HOST=${NGINX_HOST:-wordpress.local}
      - NGINX_HTTP=${NGINX_HTTP:-80}
      - NGINX_HTTPS=${NGINX_HTTPS:-443}
      - NGINX_CERT=${NGINX_CERT:-wordpress.local+1.pem}
      - NGINX_KEY=${NGINX_KEY:-wordpress.local+1-key.pem}
    volumes:
      - wp_core:/var/www/html
      - wp_uploads:/var/www/html/wp-content/uploads
      - ./wordpress/plugins:/var/www/html/wp-content/plugins
      - ./wordpress/themes:/var/www/html/wp-content/themes
      - ./templates:/etc/nginx/templates
      - ./certs:/etc/ssl
    ports:
      - ${NGINX_HTTP:-80}:80
      - ${NGINX_HTTPS:-443}:443 
    networks:
      - frontend

  redis:
    image: redis:${REDIS_VERSION:-alpine}
    networks:
      - backend

volumes:
  db_data: 
    driver: local
  wp_core:
    driver: local
  wp_uploads:
    driver: local
    
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge