version: "3"

services:

  db:
    image: mariadb:${MARIADB_VERSION:-10.7}
    container_name: db
    volumes:
      - db_data:/var/lib/mysql
      - ./conf/my.cnf:/etc/mysql/conf.d/custom.cnf
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: ${DB_NAME:-wordpress}
      MYSQL_USER: ${DB_USER:-wordpress}
      MYSQL_PASSWORD: ${DB_PASS:-password}
    networks:
      - backend

  wordpress:
    depends_on:
      - db
    build: ./wordpress
    image: wordpress-fpm:production
    container_name: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${DB_NAME:-wordpress}
      WORDPRESS_DB_USER: ${DB_USER:-wordpress}
      WORDPRESS_DB_PASSWORD: ${DB_PASS:-password}
      WORDPRESS_DEBUG: ${WP_DEBUG:-1}
      WORDPRESS_CONFIG_EXTRA: |
        /* Redis Ojbect Cache */
        define( 'WP_REDIS_HOST', 'redis' );
        define( 'WP_REDIS_PORT', 6379 );
    volumes:
      - wp_data:/var/www/html
      - ./conf/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ~/.ssh/id_rsa/:/root/.ssh/id_rsa
    networks:
      - frontend
      - backend

  wpcli:
    depends_on:
      - db
      - wordpress
    image: wordpress:cli
    container_name: wpcli
    user: xfs
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${DB_NAME:-wordpress}
      WORDPRESS_DB_USER: ${DB_USER:-wordpress}
      WORDPRESS_DB_PASSWORD: ${DB_PASS:-password}
      WORDPRESS_CONFIG_EXTRA: |
        /* Redis Ojbect Cache */
        define( 'WP_REDIS_HOST', 'redis' );
        define( 'WP_REDIS_PORT', 6379 );
    volumes:
      - wp_data:/var/www/html
    networks:
      - backend

  nginx:
    depends_on:
      - wordpress
    image: nginx:${NGINX_VERSION:-alpine}
    container_name: nginx
    restart: always
    environment:
      - NGINX_HOST=${NGINX_HOST:-wordpress.local}
      - NGINX_HTTP=${NGINX_HTTP:-80}
      - NGINX_HTTPS=${NGINX_HTTPS:-443}
      - NGINX_CERT=${NGINX_CERT:-wordpress.local+1.pem}
      - NGINX_KEY=${NGINX_KEY:-wordpress.local+1-key.pem}
    volumes:
      - wp_data:/var/www/html
      - ./templates:/etc/nginx/templates
      - ./certs:/etc/ssl
    ports:
      - ${NGINX_HTTP:-80}:80
      - ${NGINX_HTTPS:-443}:443 
    networks:
      - frontend

  redis:
    image: redis:${REDIS_VERSION:-alpine}
    container_name: redis
    restart: always
    networks:
      - backend
    volumes:
      - redis_data:/data

volumes:
  db_data: 
    driver: local
    name: wordpress-db-data
  wp_data:
    driver: local
    name: wordpress-data
  redis_data:
    driver: local
    name: wordpress-redis

networks:
  frontend:
    driver: bridge
    name: wordpress-frontend
  backend:
    driver: bridge
    name: wordpress-backend